alert('Hello World!');
console.log('secret message');
document.write("a new line");
let numberOfKittens = 5;
let numberOfPuppies = 5;
let numberOfPets = numberOfKittens + numberOfPuppies;
console.log(numberOfKittens);
document.write(numberOfKittens);
console.log(numberOfPuppies);
document.write(numberOfPuppies);
console.log(numberOfPets);
document.write(numberOfPets);